# Generated by Django 5.1.15 on 2026-03-05 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(help_text='GitHub user or org', max_length=255)),
                ('repo', models.CharField(help_text='Repository name', max_length=255)),
                ('branch', models.CharField(default='main', max_length=255)),
                ('base_path', models.CharField(blank=True, default='', help_text="Subdirectory to scan, e.g. 'src/locales'. Leave empty for repo root.", max_length=500)),
                ('file_patterns', models.JSONField(blank=True, default=list, help_text="File extensions to import, e.g. ['json','po']. Empty = auto-detect.")),
                ('access_token', models.CharField(blank=True, default='', help_text='Personal access token for private repos (optional).', max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, default='', max_length=50)),
                ('last_sync_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_repo', to='projects.project')),
            ],
            options={
                'verbose_name': 'GitHub repository',
                'verbose_name_plural': 'GitHub repositories',
            },
        ),
    ]
