# Generated by Django 5.1.15 on 2026-02-24 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("po", "PO/Gettext"),
                            ("strings", "Apple Strings"),
                            ("xliff", "XLIFF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("checksum", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_files",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslatableString",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=1000)),
                ("source_text", models.TextField()),
                ("context", models.TextField(blank=True, default="")),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                ("has_plurals", models.BooleanField(default=False)),
                ("plural_forms", models.JSONField(blank=True, default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strings",
                        to="projects.project",
                    ),
                ),
                (
                    "resource_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strings",
                        to="resources.resourcefile",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddConstraint(
            model_name="resourcefile",
            constraint=models.UniqueConstraint(
                fields=("project", "file_path", "version"),
                name="unique_project_file_version",
            ),
        ),
        migrations.AddIndex(
            model_name="translatablestring",
            index=models.Index(
                fields=["project", "is_active"], name="idx_project_active"
            ),
        ),
        migrations.AddConstraint(
            model_name="translatablestring",
            constraint=models.UniqueConstraint(
                fields=("project", "key"), name="unique_project_key"
            ),
        ),
    ]
